# Repository
owner: constructions-incongrues # Your GitHub username
repo: net.pastis-hosting.status # Your GitHub repository name

# Assignees
assignees:
  - trivoallan

# Endpoints
sites:
  # pastis-hosting.net
  - name: docker.pastis-hosting.net
    url: https://docker.pastis-hosting.net
    expectedStatusCodes:
      - 404
  - name: portainer.pastis-hosting.net
    url: https://portainer.pastis-hosting.net
  - name: traefik.pastis-hosting.net
    url: https://traefik.pastis-hosting.net
  - name: web.pastis-hosting.net
    url: https://web.pastis-hosting.net

  # arrachetoiunoeil.com
  - name: www.arrachetoiunoeil.com
    url: https://www.arrachetoiunoeil.com

  # mazemod.org
  - name: www.mazemod.org
    url: https://www.mazemod.org

  # parishq.net
  - name: www.parishq.net
    url: https://www.parishq.net

status-website:
  cname: status.pastis-hosting.net
  theme: light
  name: Pastis Hosting
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
