# Change these first
owner: constructions-incongrues # Your GitHub username
repo: net.pastis-hosting.status # Your GitHub repository name

# Add your sites here
sites:
  - name: docker.pastis-hosting.net
    url: https://docker.pastis-hosting.net
    expectedStatusCodes:
      - 404

status-website:
  cname: status.pastis-hosting.net
  theme: light
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Pastis Hosting
  introTitle: TODO
  introMessage: TOO
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
