# Repository
owner: constructions-incongrues # Your GitHub username
repo: net.pastis-hosting.status # Your GitHub repository name

# Assignees
assignees:
  - trivoallan

# Endpoints
sites:
  # pastis-hosting.net
  - name: pastis-hosting.net - docker
    url: https://docker.pastis-hosting.net
    expectedStatusCodes:
      - 404
  - name: pastis-hosting.net - portainer
    url: https://portainer.pastis-hosting.net
  - name: pastis-hosting.net - traefik
    url: https://traefik.pastis-hosting.net
  - name: pastis-hosting.net - web
    url: https://web.pastis-hosting.net

  # arrachetoiunoeil.com
  - name: arrachetoiunoeil.com
    url: https://www.arrachetoiunoeil.com

  # daheardit-records.net
  - name: daheardit-records.net - api
    url: https://api.daheardit-records.net
    expectedStatusCodes:
      - 404
  - name: daheardit-records.net - www
    url: https://www.daheardit-records.net

  # mazemod.org
  - name: mazemod.org
    url: https://www.mazemod.org

  # musiques-incongrues.net
  - name: musiques-incongrues.net
    url: https://www.musiques-incongrues.net
  - name: musiques-incongrues.net - data
    url: https://data.musiques-incongrues.net
  - name: musiques-incongrues.net - manager2000
    url: https://manager2000.musiques-incongrues.net
    expectedStatusCodes:
      - 401
  - name: musiques-incongrues.net - simbertier
    url: https://simbertier.musiques-incongrues.net
  - name: musiques-incongrues.net - zeitgeist
    url: https://zeitgeist.musiques-incongrues.net

  # musiqueapproximative.net
  - name: musiqueapproximative.net
    url: https://www.musiqueapproximative.net
  - name: musiqueapproximative.net - quickoschantenoel
    url: https://quickoschantenoel.musiqueapproximative.net
  - name: musiqueapproximative.net - radio
    url: https://radio.musiqueapproximative.net

  # ilmanquedesmots.fr
  - name: ilmanquedesmots.fr - www
    url: https://www.ilmanquedesmots.fr
  - name: ilmanquedesmots.fr - enlivrezvous
    url: https://enlivrezvous.ilmanquedesmots.fr
  - name: ilmanquedesmots.fr - grandirdansdeschamps
    url: https://grandirdansdeschamps.ilmanquedesmots.fr

  # leseditionsduchevet.fr
  - name: www.leseditionsduchevet.fr
    url: https://www.leseditionsduchevet.fr

  # ouiedire.net
  - name: www.ouiedire.net
    url: https://www.ouiedire.net

  # parishq.net
  - name: parishq.net
    url: https://parishq.net
  - name: parishq.net - computertruck
    url: https://computertruck.parishq.net
  - name: parishq.net - divag
    url: https://divag.parishq.net
  - name: parishq.net - gallery
    url: https://gallery.parishq.net
  - name: parishq.net - labitabertier
    url: https://labitabertier.parishq.net


status-website:
  cname: status.pastis-hosting.net
  theme: light
  name: Pastis Hosting
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
